<?php

return [
    'api-key' => env('GOOGLE_SERVICE_API_KEY', ''),
    'types' => explode(',', env('SAFE_LINKS_THREAT_TYPES', 'THREAT_TYPE_UNSPECIFIED,MALWARE,SOCIAL_ENGINEERING,UNWANTED_SOFTWARE,POTENTIALLY_HARMFUL_APPLICATION')),
    'platforms' => explode(',', env('SAFE_LINKS_PLATFORM_TYPES', 'PLATFORM_TYPE_UNSPECIFIED,WINDOWS,LINUX,ANDROID,OSX,IOS,ANY_PLATFORM,ALL_PLATFORMS,CHROME')),
    'entry-types' => explode(',', env('SAFE_LINKS_ENTRY_TYPES', 'THREAT_ENTRY_TYPE_UNSPECIFIED,URL,EXECUTABLE')),
];
